Update Index.cshtml
If you use ```return Json(datalist.GetData());``` you will get:

> System.InvalidOperationException: 'This request has been blocked because sensitive information could be disclosed to third party web sites when this is used in a GET request. To allow GET requests, set JsonRequestBehavior to AllowGet.'

so change to ```return Json(datalist.GetData(), JsonRequestBehavior.AllowGet);```